#!/bin/bash

# This script is called at AppVM boot if this AppVM has the qubes-firewall
# service enabled. It is executed after the empty chains for the Qubes firewall
# are created, but before rules for attached qubes are processed and inserted.
#
# It is a good place for custom rules and actions that should occur when the
# firewall service is started.
# 
# Executable scripts located in /rw/config/qubes-firewall.d are executed
# immediately before this qubes-firewall-user-script.

#see the systemd-resolved resolved.conf for further details

exec_first='
set -e -o pipefail
#allow local DNS server on firewall
#NOTE: vif+ should be the upstream interfaces
rules="$(nft list ruleset)"
  if [[ "$rules" == *"chain custom-input "* ]] ; then # >= Qubes 4.2
    ttable="qubes"
    tchain="custom-input"
  elif [[ "$rules" == *"chain INPUT "* ]] ; then # <= Qubes 4.1
    ttable="filter"
    tchain="INPUT"
  else
    exit 1
  fi
nft insert rule ip "$ttable" "$tchain" iifname "vif*" udp dport 53 counter accept
nft insert rule ip "$ttable" "$tchain" iifname "vif*" tcp dport 53 counter accept

#start the DNS server
#NOTE: systemd-resolved monitors /etc/hosts for changes
systemctl start systemd-resolved'

{ dns_pin2hosts "daemon" --exec-first "$exec_first" |& logger -t "dns_pin2hosts" ; } &
disown
